C***********************************************************************
C     MAIN2.INC
C     ISCST2 Model Data - Array Names, Array Limits, Named Common Blocks
C
C     This Include File Declares the MODNAM Character Variable,
C     To Be INCLUDEd In All But the BLOCK DATA and ERRHDL Subprograms.
C     MODNAM Is NOT In COMMON.
C***********************************************************************

      CHARACTER MODNAM*6
